# Generated by Django 4.2 on 2023-05-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя покупателя', max_length=20, verbose_name='Имя покупателя')),
                ('email', models.EmailField(help_text='Введите e-mail', max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(help_text='Введите адрес', max_length=50, verbose_name='Адрес')),
                ('city', models.CharField(help_text='Введите город', max_length=20, verbose_name='Город')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания заказа', verbose_name='Дата создания заказа')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата изменения заказа', verbose_name='Дата изменения заказа')),
                ('paid', models.BooleanField(default=False, help_text='Оплачен', verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.orderinformation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
            ],
            options={
                'verbose_name': 'Заказанный продукт',
                'verbose_name_plural': 'Заказанные продукты',
                'ordering': ('-order',),
            },
        ),
    ]
